Search.appendIndex(
    [
                {
            "fqsen": "\\Database\\Factories\\UserFactory",
            "name": "UserFactory",
            "summary": "",
            "url": "classes/Database-Factories-UserFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-UserFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003A\u0024model",
            "name": "model",
            "summary": "The\u0020name\u0020of\u0020the\u0020factory\u0027s\u0020corresponding\u0020model.",
            "url": "classes/Database-Factories-UserFactory.html#property_model"
        },                {
            "fqsen": "\\CreateUsersTable",
            "name": "CreateUsersTable",
            "summary": "",
            "url": "classes/CreateUsersTable.html"
        },                {
            "fqsen": "\\CreateUsersTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateUsersTable.html#method_up"
        },                {
            "fqsen": "\\CreateUsersTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateUsersTable.html#method_down"
        },                {
            "fqsen": "\\CreatePasswordResetsTable",
            "name": "CreatePasswordResetsTable",
            "summary": "",
            "url": "classes/CreatePasswordResetsTable.html"
        },                {
            "fqsen": "\\CreatePasswordResetsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreatePasswordResetsTable.html#method_up"
        },                {
            "fqsen": "\\CreatePasswordResetsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreatePasswordResetsTable.html#method_down"
        },                {
            "fqsen": "\\CreateFailedJobsTable",
            "name": "CreateFailedJobsTable",
            "summary": "",
            "url": "classes/CreateFailedJobsTable.html"
        },                {
            "fqsen": "\\CreateFailedJobsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateFailedJobsTable.html#method_up"
        },                {
            "fqsen": "\\CreateFailedJobsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateFailedJobsTable.html#method_down"
        },                {
            "fqsen": "\\CreateSecResourcesTable",
            "name": "CreateSecResourcesTable",
            "summary": "",
            "url": "classes/CreateSecResourcesTable.html"
        },                {
            "fqsen": "\\CreateSecResourcesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSecResourcesTable.html#method_up"
        },                {
            "fqsen": "\\CreateSecResourcesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSecResourcesTable.html#method_down"
        },                {
            "fqsen": "\\CreateSecRolesTable",
            "name": "CreateSecRolesTable",
            "summary": "",
            "url": "classes/CreateSecRolesTable.html"
        },                {
            "fqsen": "\\CreateSecRolesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSecRolesTable.html#method_up"
        },                {
            "fqsen": "\\CreateSecRolesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSecRolesTable.html#method_down"
        },                {
            "fqsen": "\\CreateSecUserRolesTable",
            "name": "CreateSecUserRolesTable",
            "summary": "",
            "url": "classes/CreateSecUserRolesTable.html"
        },                {
            "fqsen": "\\CreateSecUserRolesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSecUserRolesTable.html#method_up"
        },                {
            "fqsen": "\\CreateSecUserRolesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSecUserRolesTable.html#method_down"
        },                {
            "fqsen": "\\CreateSecRolePermissionInfosTable",
            "name": "CreateSecRolePermissionInfosTable",
            "summary": "",
            "url": "classes/CreateSecRolePermissionInfosTable.html"
        },                {
            "fqsen": "\\CreateSecRolePermissionInfosTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSecRolePermissionInfosTable.html#method_up"
        },                {
            "fqsen": "\\CreateSecRolePermissionInfosTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSecRolePermissionInfosTable.html#method_down"
        },                {
            "fqsen": "\\CreateSecResourcePermissionsTable",
            "name": "CreateSecResourcePermissionsTable",
            "summary": "",
            "url": "classes/CreateSecResourcePermissionsTable.html"
        },                {
            "fqsen": "\\CreateSecResourcePermissionsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSecResourcePermissionsTable.html#method_up"
        },                {
            "fqsen": "\\CreateSecResourcePermissionsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSecResourcePermissionsTable.html#method_down"
        },                {
            "fqsen": "\\CreateSecRolePermissionsTable",
            "name": "CreateSecRolePermissionsTable",
            "summary": "",
            "url": "classes/CreateSecRolePermissionsTable.html"
        },                {
            "fqsen": "\\CreateSecRolePermissionsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSecRolePermissionsTable.html#method_up"
        },                {
            "fqsen": "\\CreateSecRolePermissionsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSecRolePermissionsTable.html#method_down"
        },                {
            "fqsen": "\\AddNewColumnUsersTable",
            "name": "AddNewColumnUsersTable",
            "summary": "",
            "url": "classes/AddNewColumnUsersTable.html"
        },                {
            "fqsen": "\\AddNewColumnUsersTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddNewColumnUsersTable.html#method_up"
        },                {
            "fqsen": "\\AddNewColumnUsersTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddNewColumnUsersTable.html#method_down"
        },                {
            "fqsen": "\\AddNewColumnsToUsers",
            "name": "AddNewColumnsToUsers",
            "summary": "",
            "url": "classes/AddNewColumnsToUsers.html"
        },                {
            "fqsen": "\\AddNewColumnsToUsers\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddNewColumnsToUsers.html#method_up"
        },                {
            "fqsen": "\\AddNewColumnsToUsers\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddNewColumnsToUsers.html#method_down"
        },                {
            "fqsen": "\\AddNewColumnToSecRole",
            "name": "AddNewColumnToSecRole",
            "summary": "",
            "url": "classes/AddNewColumnToSecRole.html"
        },                {
            "fqsen": "\\AddNewColumnToSecRole\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddNewColumnToSecRole.html#method_up"
        },                {
            "fqsen": "\\AddNewColumnToSecRole\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddNewColumnToSecRole.html#method_down"
        },                {
            "fqsen": "\\AddNewColumnSecResourcesAndSecRolePermInfo",
            "name": "AddNewColumnSecResourcesAndSecRolePermInfo",
            "summary": "",
            "url": "classes/AddNewColumnSecResourcesAndSecRolePermInfo.html"
        },                {
            "fqsen": "\\AddNewColumnSecResourcesAndSecRolePermInfo\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddNewColumnSecResourcesAndSecRolePermInfo.html#method_up"
        },                {
            "fqsen": "\\AddNewColumnSecResourcesAndSecRolePermInfo\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddNewColumnSecResourcesAndSecRolePermInfo.html#method_down"
        },                {
            "fqsen": "\\CreateHrmDepartmentsTable",
            "name": "CreateHrmDepartmentsTable",
            "summary": "",
            "url": "classes/CreateHrmDepartmentsTable.html"
        },                {
            "fqsen": "\\CreateHrmDepartmentsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateHrmDepartmentsTable.html#method_up"
        },                {
            "fqsen": "\\CreateHrmDepartmentsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateHrmDepartmentsTable.html#method_down"
        },                {
            "fqsen": "\\CreateSchServiceCategoriesTable",
            "name": "CreateSchServiceCategoriesTable",
            "summary": "",
            "url": "classes/CreateSchServiceCategoriesTable.html"
        },                {
            "fqsen": "\\CreateSchServiceCategoriesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSchServiceCategoriesTable.html#method_up"
        },                {
            "fqsen": "\\CreateSchServiceCategoriesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSchServiceCategoriesTable.html#method_down"
        },                {
            "fqsen": "\\CreateHrmDesignationsTable",
            "name": "CreateHrmDesignationsTable",
            "summary": "",
            "url": "classes/CreateHrmDesignationsTable.html"
        },                {
            "fqsen": "\\CreateHrmDesignationsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateHrmDesignationsTable.html#method_up"
        },                {
            "fqsen": "\\CreateHrmDesignationsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateHrmDesignationsTable.html#method_down"
        },                {
            "fqsen": "\\CreateCmnCompaniesTable",
            "name": "CreateCmnCompaniesTable",
            "summary": "",
            "url": "classes/CreateCmnCompaniesTable.html"
        },                {
            "fqsen": "\\CreateCmnCompaniesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCmnCompaniesTable.html#method_up"
        },                {
            "fqsen": "\\CreateCmnCompaniesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCmnCompaniesTable.html#method_down"
        },                {
            "fqsen": "\\CreateCmnPaymentTypesTable",
            "name": "CreateCmnPaymentTypesTable",
            "summary": "",
            "url": "classes/CreateCmnPaymentTypesTable.html"
        },                {
            "fqsen": "\\CreateCmnPaymentTypesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCmnPaymentTypesTable.html#method_up"
        },                {
            "fqsen": "\\CreateCmnPaymentTypesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCmnPaymentTypesTable.html#method_down"
        },                {
            "fqsen": "\\CreateCmnBranchesTable",
            "name": "CreateCmnBranchesTable",
            "summary": "",
            "url": "classes/CreateCmnBranchesTable.html"
        },                {
            "fqsen": "\\CreateCmnBranchesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCmnBranchesTable.html#method_up"
        },                {
            "fqsen": "\\CreateCmnBranchesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCmnBranchesTable.html#method_down"
        },                {
            "fqsen": "\\CreateCmnBusinessHoursTable",
            "name": "CreateCmnBusinessHoursTable",
            "summary": "",
            "url": "classes/CreateCmnBusinessHoursTable.html"
        },                {
            "fqsen": "\\CreateCmnBusinessHoursTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCmnBusinessHoursTable.html#method_up"
        },                {
            "fqsen": "\\CreateCmnBusinessHoursTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCmnBusinessHoursTable.html#method_down"
        },                {
            "fqsen": "\\CreateCmnPaypalApiConfigsTable",
            "name": "CreateCmnPaypalApiConfigsTable",
            "summary": "",
            "url": "classes/CreateCmnPaypalApiConfigsTable.html"
        },                {
            "fqsen": "\\CreateCmnPaypalApiConfigsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCmnPaypalApiConfigsTable.html#method_up"
        },                {
            "fqsen": "\\CreateCmnPaypalApiConfigsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCmnPaypalApiConfigsTable.html#method_down"
        },                {
            "fqsen": "\\CreateCmnCurrencySetupsTable",
            "name": "CreateCmnCurrencySetupsTable",
            "summary": "",
            "url": "classes/CreateCmnCurrencySetupsTable.html"
        },                {
            "fqsen": "\\CreateCmnCurrencySetupsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCmnCurrencySetupsTable.html#method_up"
        },                {
            "fqsen": "\\CreateCmnCurrencySetupsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCmnCurrencySetupsTable.html#method_down"
        },                {
            "fqsen": "\\CreateSchEmployeesTable",
            "name": "CreateSchEmployeesTable",
            "summary": "",
            "url": "classes/CreateSchEmployeesTable.html"
        },                {
            "fqsen": "\\CreateSchEmployeesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSchEmployeesTable.html#method_up"
        },                {
            "fqsen": "\\CreateSchEmployeesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSchEmployeesTable.html#method_down"
        },                {
            "fqsen": "\\CreateSchServicesTable",
            "name": "CreateSchServicesTable",
            "summary": "",
            "url": "classes/CreateSchServicesTable.html"
        },                {
            "fqsen": "\\CreateSchServicesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSchServicesTable.html#method_up"
        },                {
            "fqsen": "\\CreateSchServicesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSchServicesTable.html#method_down"
        },                {
            "fqsen": "\\CreateSchEmployeeSchedulesTable",
            "name": "CreateSchEmployeeSchedulesTable",
            "summary": "",
            "url": "classes/CreateSchEmployeeSchedulesTable.html"
        },                {
            "fqsen": "\\CreateSchEmployeeSchedulesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSchEmployeeSchedulesTable.html#method_up"
        },                {
            "fqsen": "\\CreateSchEmployeeSchedulesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSchEmployeeSchedulesTable.html#method_down"
        },                {
            "fqsen": "\\CreateSchEmployeeServicesTable",
            "name": "CreateSchEmployeeServicesTable",
            "summary": "",
            "url": "classes/CreateSchEmployeeServicesTable.html"
        },                {
            "fqsen": "\\CreateSchEmployeeServicesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSchEmployeeServicesTable.html#method_up"
        },                {
            "fqsen": "\\CreateSchEmployeeServicesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSchEmployeeServicesTable.html#method_down"
        },                {
            "fqsen": "\\CreateSchEmployeeOffdaysTable",
            "name": "CreateSchEmployeeOffdaysTable",
            "summary": "",
            "url": "classes/CreateSchEmployeeOffdaysTable.html"
        },                {
            "fqsen": "\\CreateSchEmployeeOffdaysTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSchEmployeeOffdaysTable.html#method_up"
        },                {
            "fqsen": "\\CreateSchEmployeeOffdaysTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSchEmployeeOffdaysTable.html#method_down"
        },                {
            "fqsen": "\\AlterCmnBusinessHoursTable",
            "name": "AlterCmnBusinessHoursTable",
            "summary": "",
            "url": "classes/AlterCmnBusinessHoursTable.html"
        },                {
            "fqsen": "\\AlterCmnBusinessHoursTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AlterCmnBusinessHoursTable.html#method_up"
        },                {
            "fqsen": "\\AlterCmnBusinessHoursTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AlterCmnBusinessHoursTable.html#method_down"
        },                {
            "fqsen": "\\CreateCmnCustomersTable",
            "name": "CreateCmnCustomersTable",
            "summary": "",
            "url": "classes/CreateCmnCustomersTable.html"
        },                {
            "fqsen": "\\CreateCmnCustomersTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCmnCustomersTable.html#method_up"
        },                {
            "fqsen": "\\CreateCmnCustomersTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCmnCustomersTable.html#method_down"
        },                {
            "fqsen": "\\CreateCmnBusinessHolidaysTable",
            "name": "CreateCmnBusinessHolidaysTable",
            "summary": "",
            "url": "classes/CreateCmnBusinessHolidaysTable.html"
        },                {
            "fqsen": "\\CreateCmnBusinessHolidaysTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCmnBusinessHolidaysTable.html#method_up"
        },                {
            "fqsen": "\\CreateCmnBusinessHolidaysTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCmnBusinessHolidaysTable.html#method_down"
        },                {
            "fqsen": "\\CreateSchServiceBookingsTable",
            "name": "CreateSchServiceBookingsTable",
            "summary": "",
            "url": "classes/CreateSchServiceBookingsTable.html"
        },                {
            "fqsen": "\\CreateSchServiceBookingsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSchServiceBookingsTable.html#method_up"
        },                {
            "fqsen": "\\CreateSchServiceBookingsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSchServiceBookingsTable.html#method_down"
        },                {
            "fqsen": "\\CreateCmnPaymentInfosTable",
            "name": "CreateCmnPaymentInfosTable",
            "summary": "",
            "url": "classes/CreateCmnPaymentInfosTable.html"
        },                {
            "fqsen": "\\CreateCmnPaymentInfosTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCmnPaymentInfosTable.html#method_up"
        },                {
            "fqsen": "\\CreateCmnPaymentInfosTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCmnPaymentInfosTable.html#method_down"
        },                {
            "fqsen": "\\CreateSiteMenusTable",
            "name": "CreateSiteMenusTable",
            "summary": "",
            "url": "classes/CreateSiteMenusTable.html"
        },                {
            "fqsen": "\\CreateSiteMenusTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSiteMenusTable.html#method_up"
        },                {
            "fqsen": "\\CreateSiteMenusTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSiteMenusTable.html#method_down"
        },                {
            "fqsen": "\\CreateSiteAppearancesTable",
            "name": "CreateSiteAppearancesTable",
            "summary": "",
            "url": "classes/CreateSiteAppearancesTable.html"
        },                {
            "fqsen": "\\CreateSiteAppearancesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSiteAppearancesTable.html#method_up"
        },                {
            "fqsen": "\\CreateSiteAppearancesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSiteAppearancesTable.html#method_down"
        },                {
            "fqsen": "\\CreateSiteClientTestimonialsTable",
            "name": "CreateSiteClientTestimonialsTable",
            "summary": "",
            "url": "classes/CreateSiteClientTestimonialsTable.html"
        },                {
            "fqsen": "\\CreateSiteClientTestimonialsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSiteClientTestimonialsTable.html#method_up"
        },                {
            "fqsen": "\\CreateSiteClientTestimonialsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSiteClientTestimonialsTable.html#method_down"
        },                {
            "fqsen": "\\CreateSitePhotoGalleriesTable",
            "name": "CreateSitePhotoGalleriesTable",
            "summary": "",
            "url": "classes/CreateSitePhotoGalleriesTable.html"
        },                {
            "fqsen": "\\CreateSitePhotoGalleriesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSitePhotoGalleriesTable.html#method_up"
        },                {
            "fqsen": "\\CreateSitePhotoGalleriesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSitePhotoGalleriesTable.html#method_down"
        },                {
            "fqsen": "\\CreateSiteAboutUsTable",
            "name": "CreateSiteAboutUsTable",
            "summary": "",
            "url": "classes/CreateSiteAboutUsTable.html"
        },                {
            "fqsen": "\\CreateSiteAboutUsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSiteAboutUsTable.html#method_up"
        },                {
            "fqsen": "\\CreateSiteAboutUsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSiteAboutUsTable.html#method_down"
        },                {
            "fqsen": "\\CreateSiteFrequentlyAskedQuestionsTable",
            "name": "CreateSiteFrequentlyAskedQuestionsTable",
            "summary": "",
            "url": "classes/CreateSiteFrequentlyAskedQuestionsTable.html"
        },                {
            "fqsen": "\\CreateSiteFrequentlyAskedQuestionsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSiteFrequentlyAskedQuestionsTable.html#method_up"
        },                {
            "fqsen": "\\CreateSiteFrequentlyAskedQuestionsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSiteFrequentlyAskedQuestionsTable.html#method_down"
        },                {
            "fqsen": "\\CreateSiteGoogleMaps",
            "name": "CreateSiteGoogleMaps",
            "summary": "",
            "url": "classes/CreateSiteGoogleMaps.html"
        },                {
            "fqsen": "\\CreateSiteGoogleMaps\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSiteGoogleMaps.html#method_up"
        },                {
            "fqsen": "\\CreateSiteGoogleMaps\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSiteGoogleMaps.html#method_down"
        },                {
            "fqsen": "\\CreateSiteTermsAndConditionsTable",
            "name": "CreateSiteTermsAndConditionsTable",
            "summary": "",
            "url": "classes/CreateSiteTermsAndConditionsTable.html"
        },                {
            "fqsen": "\\CreateSiteTermsAndConditionsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSiteTermsAndConditionsTable.html#method_up"
        },                {
            "fqsen": "\\CreateSiteTermsAndConditionsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSiteTermsAndConditionsTable.html#method_down"
        },                {
            "fqsen": "\\CreateSecUserBranchesTable",
            "name": "CreateSecUserBranchesTable",
            "summary": "",
            "url": "classes/CreateSecUserBranchesTable.html"
        },                {
            "fqsen": "\\CreateSecUserBranchesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSecUserBranchesTable.html#method_up"
        },                {
            "fqsen": "\\CreateSecUserBranchesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSecUserBranchesTable.html#method_down"
        },                {
            "fqsen": "\\AddNewColumnSchEmployeeIdUsersTable",
            "name": "AddNewColumnSchEmployeeIdUsersTable",
            "summary": "",
            "url": "classes/AddNewColumnSchEmployeeIdUsersTable.html"
        },                {
            "fqsen": "\\AddNewColumnSchEmployeeIdUsersTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddNewColumnSchEmployeeIdUsersTable.html#method_up"
        },                {
            "fqsen": "\\AddNewColumnSchEmployeeIdUsersTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddNewColumnSchEmployeeIdUsersTable.html#method_down"
        },                {
            "fqsen": "\\InsertOrUpdateUserRoleOtherInitInfo",
            "name": "InsertOrUpdateUserRoleOtherInitInfo",
            "summary": "",
            "url": "classes/InsertOrUpdateUserRoleOtherInitInfo.html"
        },                {
            "fqsen": "\\InsertOrUpdateUserRoleOtherInitInfo\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "This\u0020method\u0020insert\u0020default\u0020configuration\nAuthor\u003A\u0020kaysar\nDate\u003A\u002022\u002DJan\u002D2021",
            "url": "classes/InsertOrUpdateUserRoleOtherInitInfo.html#method_up"
        },                {
            "fqsen": "\\InsertOrUpdateUserRoleOtherInitInfo\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/InsertOrUpdateUserRoleOtherInitInfo.html#method_down"
        },                {
            "fqsen": "\\UpdateSiteFrequentlyAskedQuestionsTable",
            "name": "UpdateSiteFrequentlyAskedQuestionsTable",
            "summary": "",
            "url": "classes/UpdateSiteFrequentlyAskedQuestionsTable.html"
        },                {
            "fqsen": "\\UpdateSiteFrequentlyAskedQuestionsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/UpdateSiteFrequentlyAskedQuestionsTable.html#method_up"
        },                {
            "fqsen": "\\UpdateSiteFrequentlyAskedQuestionsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/UpdateSiteFrequentlyAskedQuestionsTable.html#method_down"
        },                {
            "fqsen": "\\CreateCmnStripeApiConfigsTable",
            "name": "CreateCmnStripeApiConfigsTable",
            "summary": "",
            "url": "classes/CreateCmnStripeApiConfigsTable.html"
        },                {
            "fqsen": "\\CreateCmnStripeApiConfigsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCmnStripeApiConfigsTable.html#method_up"
        },                {
            "fqsen": "\\CreateCmnStripeApiConfigsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCmnStripeApiConfigsTable.html#method_down"
        },                {
            "fqsen": "\\CreateCmnLanguagesTable",
            "name": "CreateCmnLanguagesTable",
            "summary": "",
            "url": "classes/CreateCmnLanguagesTable.html"
        },                {
            "fqsen": "\\CreateCmnLanguagesTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCmnLanguagesTable.html#method_up"
        },                {
            "fqsen": "\\CreateCmnLanguagesTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCmnLanguagesTable.html#method_down"
        },                {
            "fqsen": "\\CreateCmnTranslationsTable",
            "name": "CreateCmnTranslationsTable",
            "summary": "",
            "url": "classes/CreateCmnTranslationsTable.html"
        },                {
            "fqsen": "\\CreateCmnTranslationsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCmnTranslationsTable.html#method_up"
        },                {
            "fqsen": "\\CreateCmnTranslationsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCmnTranslationsTable.html#method_down"
        },                {
            "fqsen": "\\InsertUpdateVersionUpdatedDataDependency",
            "name": "InsertUpdateVersionUpdatedDataDependency",
            "summary": "",
            "url": "classes/InsertUpdateVersionUpdatedDataDependency.html"
        },                {
            "fqsen": "\\InsertUpdateVersionUpdatedDataDependency\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/InsertUpdateVersionUpdatedDataDependency.html#method_up"
        },                {
            "fqsen": "\\InsertUpdateVersionUpdatedDataDependency\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/InsertUpdateVersionUpdatedDataDependency.html#method_down"
        },                {
            "fqsen": "\\InsertTranslationDefaultEnLanguage",
            "name": "InsertTranslationDefaultEnLanguage",
            "summary": "",
            "url": "classes/InsertTranslationDefaultEnLanguage.html"
        },                {
            "fqsen": "\\InsertTranslationDefaultEnLanguage\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/InsertTranslationDefaultEnLanguage.html#method_up"
        },                {
            "fqsen": "\\InsertTranslationDefaultEnLanguage\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/InsertTranslationDefaultEnLanguage.html#method_down"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder",
            "name": "DatabaseSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-DatabaseSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Seed\u0020the\u0020application\u0027s\u0020database.",
            "url": "classes/Database-Seeders-DatabaseSeeder.html#method_run"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Database\\Factories",
            "name": "Factories",
            "summary": "",
            "url": "namespaces/database-factories.html"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "namespaces/database.html"
        },                {
            "fqsen": "\\Database\\Seeders",
            "name": "Seeders",
            "summary": "",
            "url": "namespaces/database-seeders.html"
        }            ]
);
